### ISSUE TITLE
Abort for grid input of type 2N

### ISSUE THREAD

**Issue by jdonners** [jdonners/afid#4]
Vamsi Spandan wrote: Add an error-code when the grid input in the "bou.in" is of the form "2N"

There is no error generated. fftw is slower for grid input of form "2n" (NX,NY are even). Would it be useful if the program stops and prompts the user to input (NX,NY) of the form "2n+1" in 'bou.in' ?

**Comment by stevensrjam** [comment]
This issue is fixed now. Added an update to the code, which factorizes the input grid resolutions in the horizontal direction to make sure it is a combination of small prime factors.
